/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-105780-g0d0002cd20-20220227"
#endif /* AVUTIL_FFVERSION_H */
